pyExceptions/__init__.py,sha256=DyfvklegMaJ3E__e2UzWs_Xw80WiLQOAI4ts4VaBlk4,3027
pyExceptions-0.1.7.dist-info/LICENSE.md,sha256=DF4r-Jbsz_ZASY4VjV0ZZVaaHYkH9a20BkVExpq8doE,10571
pyExceptions-0.1.7.dist-info/METADATA,sha256=iKfQv5IVd_jvwQYF_FWfvW42TcXNxQjr_1_vxIgS0-c,2051
pyExceptions-0.1.7.dist-info/WHEEL,sha256=p46_5Uhzqz6AzeSosiOnxK-zmFja1i22CrQCjmYe8ec,92
pyExceptions-0.1.7.dist-info/top_level.txt,sha256=FCUx2KjHbxV3j3LdKBNNoUArrjEkFQTn9tzdqg_RCWs,13
pyExceptions-0.1.7.dist-info/RECORD,,
